'''
IMPLEMENTAR LOS HILOS DE EJECUCION Y COMPROBAR SU FUNCIONAMIENTO

MODIFICAR EL NOMBRE DE LAS VARIABLES PARA QUE SEAN MAS "INFORMATIVAS"

COMENTAR EL CODIGO

QUIZA, AÑADIR ALGUN DATO MAS QUE MOSTAR POR PANTALLA??

'''